In [1]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [7]:
dataset['sex']=dataset['sex'].astype('category')
dataset['sex']=dataset['sex'].cat.codes
dataset

      age  sex     bmi  children smoker      charges
0      19    0  27.900         0    yes  16884.92400
1      18    1  33.770         1     no   1725.55230
2      28    1  33.000         3     no   4449.46200
3      33    1  22.705         0     no  21984.47061
4      32    1  28.880         0     no   3866.85520
...   ...  ...     ...       ...    ...          ...
1333   50    1  30.970         3     no  10600.54830
1334   18    0  31.920         0     no   2205.98080
1335   18    0  36.850         0     no   1629.83350
1336   21    0  25.800         0     no   2007.94500
1337   61    0  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [9]:
dataset['smoker']=dataset['smoker'].astype('category')
dataset['smoker']=dataset['smoker'].cat.codes
dataset

      age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [11]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [13]:
independent=dataset.drop(columns='charges')
independent

      age  sex     bmi  children  smoker
0      19    0  27.900         0       1
1      18    1  33.770         1       0
2      28    1  33.000         3       0
3      33    1  22.705         0       0
4      32    1  28.880         0       0
...   ...  ...     ...       ...     ...
1333   50    1  30.970         3       0
1334   18    0  31.920         0       0
1335   18    0  36.850         0       0
1336   21    0  25.800         0       0
1337   61    0  29.070         0       1

[1338 rows x 5 columns]

In [15]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'], 'splitter':['best','random'],'max_features':['auto','sqrt','log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
39 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.68115108 0.60872785 0.60749243 0.68013586
        nan        nan 0.72526964 0.64940973 0.67531457 0.67746925
        nan        nan 0.73300702 0.6769428  0.69949325 0.68586442
        nan        nan 0.69857011 0.67410265 0.64947485 0.62758788]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [23]:
re=grid.cv_results_
print("The R_Score value for best parameter{}:".format(grid.best_params_))

The R_Score value for best parameter{'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'}:

In [25]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003203,0.000400,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002003,0.000633,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.011408,0.000490,0.006205,0.000400,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.759681,0.458629,0.754044,0.691083,0.742319,0.681151,0.113874,6
3,0.010007,0.001096,0.005605,0.000800,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.673043,0.565146,0.614949,0.625656,0.564845,0.608728,0.040711,15
4,0.011408,0.001020,0.005604,0.000801,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.670760,0.391520,0.744003,0.664006,0.567172,0.607492,0.121739,16
5,0.011209,0.001722,0.006805,0.001168,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.718974,0.644074,0.678173,0.642973,0.716485,0.680136,0.033211,7
6,0.003002,0.001266,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002601,0.000491,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.011208,0.001471,0.005603,0.000490,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.796330,0.592562,0.765845,0.735206,0.736405,0.725270,0.070043,2
9,0.010207,0.000750,0.006404,0.000801,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.681400,0.506254,0.693680,0.686336,0.679378,0.649410,0.071747,13
10,0.011808,0.002136,0.006204,0.000400,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.737142,0.595128,0.672727,0.719724,0.651852,0.675315,0.050560,10
11,0.010006,0.000895,0.006004,0.000633,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.703562,0.634170,0.730807,0.669951,0.648855,0.677469,0.035429,8
12,0.002401,0.000801,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.002202,0.000400,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.043830,0.011847,0.005404,0.000490,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.716660,0.666797,0.744428,0.780179,0.756970,0.733007,0.038938,1
15,0.031222,0.003972,0.004803,0.000749,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.682108,0.615223,0.713220,0.666782,0.707381,0.676943,0.035162,9
16,0.035024,0.003580,0.004804,0.000749,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.706816,0.599553,0.738479,0.714359,0.738260,0.699493,0.051547,3
17,0.026218,0.002228,0.005804,0.000401,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.644486,0.681485,0.711038,0.737917,0.654396,0.685864,0.034827,5
18,0.002201,0.000400,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001800,0.000400,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.012407,0.001498,0.005605,0.000801,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.721469,0.614260,0.705152,0.742562,0.709407,0.698570,0.044110,4
21,0.009806,0.000979,0.005003,0.000633,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.669859,0.559849,0.784159,0.704699,0.651947,0.674103,0.072954,11
22,0.011806,0.001327,0.005605,0.000491,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.690120,0.616232,0.603057,0.753607,0.584358,0.649475,0.063238,12
23,0.010006,0.000001,0.005604,0.000490,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.676649,0.504392,0.736729,0.651715,0.568455,0.627588,0.081945,14

In [27]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_input=float(input("Sex male 0 or1:"))
smoker_input=float(input("SMOKER yes 0 or1:"))

Age: 4
BMI: 56
Children: 5
Sex male 0 or1: 5
SMOKER yes 0 or1: 3

In [29]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_input,smoker_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16420.49455]

C:\Users\JOSE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(